$kind: http-request
name: product:createNewProduct
url: localhost:3003/admin/product/create
method: POST
body:
  type: formdata
  content:
    - type: text
      key: productCollection
      value: DISH
      description: ""
      disabled: false
    - type: text
      key: productName
      value: Steak
      description: ""
      disabled: false
    - type: text
      key: productPrice
      value: "15"
      description: ""
      disabled: false
    - type: text
      key: productLeftCount
      value: "100"
      description: ""
      disabled: false
    - type: text
      key: productSize
      value: NORMAL
      description: ""
      disabled: false
    - type: text
      key: productVolume
      value: "1"
      description: ""
      disabled: true
    - type: text
      key: productDesc
      value: Delicious meal
      description: ""
      disabled: false
    - type: file
      key: productImages
      src:
        - /Users/ismigulkhasanboeva/Downloads/k.jpeg
        - /Users/ismigulkhasanboeva/Downloads/kebab.jpeg
        - /Users/ismigulkhasanboeva/Downloads/Lula_kebab_2.jpg
        - /Users/ismigulkhasanboeva/Downloads/tavuk_sis1-600x450.webp
      disabled: false
order: 9000
